Sprint1
infabeti/R0-Josu-Gorka-Adrian pull request #1
Opened 2020-10-01 11:35 UTC by josu1199

Pull request Sprint1

2020-10-02 06:36 UTC, infabeti commented on Biblioteca/.classpath
> +	<classpathentry kind="lib" path="C:/Eclipse_Workspace/R0-Josu-Gorka-Adrian/Librerias/pdfbox-app-2.0.21.jar"/>
El path no debe de depender de donde esté el workspace

2020-10-02 06:38 UTC, infabeti commented on Biblioteca/src/main/java/reto/Aplicacion.java
> +		iniciar.setVisible(true);
Esto hay que hacerlo en la vista

2020-10-02 06:39 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +	public Lector() {
sino lo vais a recargar no es necesario

2020-10-02 06:39 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String LeerExtension(String Ruta) throws IOException {
No propagues las excepciones. Tratalas en el método

2020-10-02 06:40 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +		return true;
tabula

2020-10-02 06:40 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			try {
cuida las tabulaciones

2020-10-02 06:41 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +				e.printStackTrace();
Tendrás que dar una solución a este error

2020-10-02 06:41 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			try {
tabulaciones...

2020-10-02 06:42 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			} catch (IOException e) {
Dá una solución

2020-10-02 06:42 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +            if (!document.isEncrypted()) {
tabulaciones

2020-10-02 06:42 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
Tendrás que dar una solución

2020-10-02 06:43 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +       btnSeleccionar.addActionListener(new ActionListener() {
todo a la misma altura

2020-10-02 06:43 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +               File ruta = new File("src/Almacen");
esto no lo debería de hacer la vista

2020-10-02 06:44 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testMainIncorrecto() throws IOException {
Como va a lanzar una excepción un test? Que estais probando?

2020-10-02 06:45 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerDOC() throws IOException {
Un test no puede propagar una excepcion

2020-10-02 06:45 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerDOCX() throws IOException {
+1

2020-10-02 06:45 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerPDF() throws IOException {
+1

2020-10-02 06:46 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerXML() throws IOException {
+1

2020-10-02 06:46 UTC, infabeti requested changes
Ir arreglando lo que os he comentado

2020-10-03 10:50 UTC, Adrian1MT commented on Biblioteca/.classpath
> +	<classpathentry kind="lib" path="C:/Eclipse_Workspace/R0-Josu-Gorka-Adrian/Librerias/pdfbox-app-2.0.21.jar"/>
Arreglado

2020-10-03 10:52 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +	public Lector() {
ya esta eliminada

2020-10-03 10:56 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String LeerExtension(String Ruta) throws IOException {
corregida

2020-10-03 10:56 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +		return true;
corregida

2020-10-03 10:57 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +			try {
corregida

2020-10-03 10:58 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +			try {
corregida

2020-10-03 10:58 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +            if (!document.isEncrypted()) {
corregida

2020-10-03 11:16 UTC, Adrian1MT commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testMainIncorrecto() throws IOException {
Corregido

2020-10-03 11:16 UTC, Adrian1MT commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerDOC() throws IOException {
Corregido

2020-10-03 11:16 UTC, Adrian1MT commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerDOCX() throws IOException {
Corregido

2020-10-03 11:16 UTC, Adrian1MT commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerPDF() throws IOException {
Corregido

2020-10-03 11:16 UTC, Adrian1MT commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +	public void testLeerXML() throws IOException {
Corregido

2020-10-04 10:48 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Aplicacion.java
> +		iniciar.setVisible(true);
corregido

2020-10-04 13:32 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +				e.printStackTrace();
Corregido

2020-10-04 13:32 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +			} catch (IOException e) {
Corregido

2020-10-04 13:32 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
Corregido

2020-10-05 16:26 UTC, infabeti commented on Biblioteca/.classpath
> +	<classpathentry kind="lib" path="C:/Eclipse_Worskspace/R0-Josu-Gorka-Adrian/Biblioteca/src/Librerias/pdfbox-app-2.0.21.jar"/>
El path no tiene que depender de la ubicacion del workspace

2020-10-05 16:28 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero DOC mal definida");
Puede haber más fallos que ese, pon un mensaje mas genérico

2020-10-05 16:28 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero DOCX mal definida");
Puede haber más fallos que ese, pon un mensaje mas genérico

2020-10-05 16:29 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero PDF mal definida");
Puede haber más fallos que ese, pon un mensaje mas genérico y añada la traza al println

2020-10-05 16:29 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
Puede haber más fallos que ese, pon un mensaje mas genérico y añada la traza al println

2020-10-05 16:29 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +		iniciar.setVisible(true);
Esto se debería de hacer en la vista

2020-10-05 16:30 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +               File ruta = new File("src/Almacen");
Sigue sin estar corregido

2020-10-05 16:31 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertNotEquals(resultadoEsperado.trim(), resultado.trim());
El test no debería de depender de trim

2020-10-05 16:31 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
El test no debería de depender de trim

2020-10-05 16:31 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
El test no debería de depender de trim

2020-10-05 16:31 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
El test no debería de depender de trim

2020-10-05 16:31 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.replaceAll("\\s",""), resultado.replaceAll("\\s",""));
El test no debería de depender de replaceAll

2020-10-05 16:32 UTC, infabeti requested changes
Seguís sin arreglar la mayoría de las cosas que puse la última vez

2020-10-06 06:37 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +       btnSeleccionar.addActionListener(new ActionListener() {
corregido

2020-10-06 07:11 UTC, josu1199 commented on Biblioteca/.classpath
> +	<classpathentry kind="lib" path="C:/Eclipse_Worskspace/R0-Josu-Gorka-Adrian/Biblioteca/src/Librerias/pdfbox-app-2.0.21.jar"/>
Corregido

2020-10-06 07:11 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertNotEquals(resultadoEsperado.trim(), resultado.trim());
corregido

2020-10-06 07:11 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
corregido

2020-10-06 07:11 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
corregido

2020-10-06 07:12 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
corregido

2020-10-06 07:12 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.trim(), resultado.trim());
corregido

2020-10-06 07:12 UTC, josu1199 commented on Biblioteca/src/test/java/Biblioteca/TestLector.java
> +		assertEquals(resultadoEsperado.replaceAll("\\s",""), resultado.replaceAll("\\s",""));
corregido

2020-10-06 08:03 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +               File ruta = new File("src/Almacen");
Corregido

2020-10-06 08:04 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
Arreglado

2020-10-06 08:04 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero DOC mal definida");
Arreglado

2020-10-06 08:04 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero DOCX mal definida");
Arreglado

2020-10-06 08:04 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +			System.out.println("Error, Ruta del fichero PDF mal definida");
Arreglado

2020-10-06 08:23 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String LeerExtension(String Ruta){
Las variables las ponemos en minuscula, los metodos también, solo ponemos en mayuscula el nombre de las clases. Revisar el proyecto y ponerlo bien.

2020-10-06 08:24 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
No has añadido la traza al mensaje que muestras por pantalla

2020-10-06 08:24 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +		setResizable(false);
alinealo con el resto

2020-10-06 08:26 UTC, infabeti requested changes
Arreglar lo que os he puesto

2020-10-06 09:46 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String LeerExtension(String Ruta){
Corregido

2020-10-06 09:49 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +		setResizable(false);
En el eclipse nos muestra la linea correctamente alineada
![imagen](https://user-images.githubusercontent.com/60694576/95186183-ff6bae00-07c9-11eb-9f0f-0fc172458730.png)

2020-10-06 20:05 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String leerExtension(String Ruta){
Ruta en minuscula

2020-10-06 20:06 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +		}catch(Exception e) {
Sigues sin arreglarlo

2020-10-06 20:06 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +		setResizable(false);
OK

2020-10-06 20:07 UTC, infabeti reviewed
Os faltan un par de detalles

2020-10-07 07:18 UTC, josu1199 commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String leerExtension(String Ruta){
Arreglado

2020-10-07 07:30 UTC, closed without merging