Sprint2
infabeti/R0-Josu-Gorka-Adrian pull request #3
Opened 2020-10-22 06:43 UTC by josu1199

Pull request Sprint 2

2020-10-22 06:55 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
>  public class Lector {
Una clase de 350 lineas es demasiado larga. Separadlo en dos o tres clases.

2020-10-22 06:56 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
>  	public static void main(String[] args) {
No pongais el main y una ventana en la misma clase. Separalo en dos clases.

2020-10-22 06:57 UTC, infabeti requested changes
Refactorizar el código para que sea más legible.

2020-10-22 07:45 UTC, josu1199 commented on Biblioteca/src/main/java/reto/Lector.java
>  public class Lector {
Solucionado

2020-10-22 07:57 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
>  	public static void main(String[] args) {
Ya esta separado

2020-10-23 06:07 UTC, infabeti approved these changes

2020-10-23 06:07 UTC, merged