Sprint3
infabeti/R0-Josu-Gorka-Adrian pull request #4
Opened 2020-10-27 10:39 UTC by Adrian1MT

Pull request del Sprint3

2020-10-28 07:23 UTC, infabeti requested changes

2020-10-28 07:23 UTC, infabeti commented on Biblioteca/.settings/org.eclipse.jdt.core.prefs
> +<<<<<<< HEAD
merge conflict

2020-10-28 07:44 UTC, infabeti commented on Biblioteca/src/main/java/reto/Escritor.java
>  		Comprobar comprobar = new Comprobar();
Que comprueba? No le puedes poner un nombre más representativo?

2020-10-28 07:44 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
>  		Comprobar comprobar = new Comprobar();
+1

2020-10-28 07:45 UTC, infabeti commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String modificarRuta(String Ruta) {
Este método estaría mejor en otra clase

2020-10-28 07:46 UTC, infabeti commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +					TipoArchivo.setText("Estas en " + nombre);
Haceis demasiadas cosas en la vista. Muchas de estas operaciones se pueden hacer fuera de la vista.

2020-10-28 07:47 UTC, infabeti commented on Biblioteca/src/main/java/reto/VisualizarHtml.java
> +	public static void main(String[] args) {
Dos main?

2020-10-28 07:47 UTC, infabeti commented on Biblioteca/src/main/java/reto/VisualizarHtml.java
> +	public void conexionhtml(String ruta) {
Tratamiento de errores en la vista?

2020-10-28 07:48 UTC, infabeti commented on Biblioteca/src/main/java/reto/escribirDOCX.java
> +		File error = new File("src/Errores/errores.txt");
El nombre del fichero no debería ser un final

2020-10-28 07:48 UTC, infabeti commented on Biblioteca/src/main/java/reto/escribirHTML.java
> +		File error = new File("src/Errores/errores.txt");
+1

2020-10-28 07:50 UTC, infabeti commented on Biblioteca/src/main/java/reto/escribirXML.java
> +	public void escribirXML(String ruta, String contenido) {
Este método hace demasiadas cosas. No sería mejor idea separlo a su vez en varios métodos?

2020-10-28 07:50 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerDOCX.java
> +		File error = new File("src/Errores/errores.txt");
nombre final

2020-10-28 07:51 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerDOCX.java
> +			PrintStream ps = new PrintStream(new BufferedOutputStream(new FileOutputStream(error, true)), true);
Pegale un intro a esta linea o ponedlo en el lintern

2020-10-28 07:52 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerHTML.java
> +		BufferedReader br = new BufferedReader(fr);
Si te da error el primer catch tienes que hacer la segunda parte? Yo creo que no...

2020-10-28 07:52 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerPDF.java
> +		File error = new File("src/Errores/errores.txt");
final

2020-10-28 07:53 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerPDF.java
> +		try {
Un try dentro de un try? No te vale con uno?

2020-10-28 07:53 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerXML.java
> +	File error = new File("src/Errores/errores.txt");
+1

2020-10-28 07:53 UTC, infabeti commented on Biblioteca/src/main/java/reto/leerXML.java
> +	public String leerXML(String ruta) {
intentar separarlo

2020-10-28 07:54 UTC, infabeti requested changes
Os he puesto un par de comentarios. Yo os revisaré los teses cuando lo arregleis.

2020-10-28 08:06 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Escritor.java
>  		Comprobar comprobar = new Comprobar();
Arreglado

2020-10-28 08:06 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
>  		Comprobar comprobar = new Comprobar();
Arreglado

2020-10-28 08:06 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/Lector.java
> +	public String modificarRuta(String Ruta) {
Corregido

2020-10-28 08:06 UTC, GorkaCarnero commented on Biblioteca/src/main/java/reto/VisualizarHtml.java
> +	public static void main(String[] args) {
Corregido

2020-10-28 08:40 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/escribirDOCX.java
> +		File error = new File("src/Errores/errores.txt");
Corregido

2020-10-28 08:40 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/escribirHTML.java
> +		File error = new File("src/Errores/errores.txt");
Corregido

2020-10-28 08:41 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerDOCX.java
> +		File error = new File("src/Errores/errores.txt");
Corregido

2020-10-28 08:41 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerPDF.java
> +		File error = new File("src/Errores/errores.txt");
Corregido

2020-10-28 08:41 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerXML.java
> +	File error = new File("src/Errores/errores.txt");
Corregido

2020-10-28 08:59 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/VisualizarHtml.java
> +	public void conexionhtml(String ruta) {
corregido

2020-10-28 09:05 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerDOCX.java
> +			PrintStream ps = new PrintStream(new BufferedOutputStream(new FileOutputStream(error, true)), true);
Corregido

2020-10-28 18:13 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/escribirXML.java
> +	public void escribirXML(String ruta, String contenido) {
separados

2020-10-28 18:20 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerHTML.java
> +		BufferedReader br = new BufferedReader(fr);
Fue un pequeño lapsus, ya esta arreglado

2020-10-28 18:21 UTC, Adrian1MT commented on Biblioteca/src/main/java/reto/leerPDF.java
> +		try {
Corregido

2020-10-29 07:59 UTC, josu1199 commented on Biblioteca/src/main/java/reto/VentanaSeleccionArchivo.java
> +					TipoArchivo.setText("Estas en " + nombre);
Solucionado

2020-10-29 08:03 UTC, infabeti commented on Biblioteca/src/main/java/Vista/VentanaSeleccionArchivo.java
> +					TipoArchivo.setText("Estas en " + nombre);
Parte de esto no se podría hacer fuera de la vista con un método?

2020-10-29 08:04 UTC, infabeti commented on Biblioteca/src/main/java/Vista/VentanaSeleccionArchivo.java
> +				escribir.escribir(textOculto.getText(), textArea.getText());
escribir.escribir no parece el titulo mas intuituvo

2020-10-29 08:47 UTC, Adrian1MT commented on Biblioteca/src/main/java/Vista/VentanaSeleccionArchivo.java
> +				escribir.escribir(textOculto.getText(), textArea.getText());
Corregido

2020-10-29 08:49 UTC, Adrian1MT commented on Biblioteca/src/main/java/Vista/VentanaSeleccionArchivo.java
> +					TipoArchivo.setText("Estas en " + nombre);
Metodo mejorado

2020-10-29 16:53 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestEscribir.java
> +		assertEquals(resultado, resultadoEsperado);
Que estás testeando aqui?

2020-10-29 16:54 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestEscribir.java
> +		String resultado = lector.comprobarExtension("src/Almacen/prueba3.xml");
Que estás testeando aqui?

2020-10-29 16:55 UTC, infabeti commented on Biblioteca/src/test/java/Biblioteca/TestEscribir.java
> +public class TestEscribir {
Mañana miramos juntos los test en clase

2020-10-29 16:56 UTC, infabeti requested changes
Mañana miramos juntos los test en clase. Porque, parece que no sabéis muy bien lo que estáis haciendo.

2020-10-30 08:14 UTC, GorkaCarnero commented on Biblioteca/src/test/java/Biblioteca/TestEscribir.java
> +		assertEquals(resultado, resultadoEsperado);
Corregido

2020-10-30 08:31 UTC, infabeti approved these changes

2020-10-30 08:31 UTC, merged